### ISSUE TITLE
能不能把两个功能合二为一

### ISSUE THREAD

**Issue by LanYanY** [yeyt97/AirDropPlus#1]
能不能把两个功能合二为一，电脑端判断一下剪切板里的是文件还是字符，决定推送文件还是同步剪切板

**Comment by yeyt97** [comment]
这样无法推送手机剪贴板

**Comment by Darrenpig** [comment]
> 能不能把两个功能合二为一，电脑端判断一下剪切板里的是文件还是字符，决定推送文件还是同步剪切板

你的意思是整合两个快捷指令为一个吗，还是单纯想要实时同步（参考：快贴https://home.clipber.com/download/windows/）

**Comment by Darrenpig** [comment]
相比快贴的解决方案，我感觉`杰尼龟`的方案明显更优
（当然，我还没有搞清楚localstand和b开头啥的...）

**Comment by luojunyuan** [comment]
好像可以把手机接收文件和剪切板统一，但是手动接受数据和发送数据，也至少需要两个shorts。

**Comment by yeyt97** [comment]
现在合并了
