### ISSUE TITLE
应用程序无法打开，链接服务器失败

### ISSUE THREAD

**Issue by iiiiiiu** [yeyt97/AirDropPlus#18]
博主各站账号已经注销了，请问一下是不是不维护了，这个捷径和程序太好用了，好可惜

**Comment by yeyt97** [comment]
前段时间放着没管，这段时间可能会开始更新。错误提示是什么，我没遇到过你说的这个问题

**Comment by iiiiiiu** [comment]
感谢大大回复，软件太好用了，是否有打赏通道支持一下 。
另外我把报错情况说一下：
电脑1：没有报错界面，程序打开没反应，任务管理器找不到，如果此时用手机传输的话，在手机端会提示连接服务器失败，是突然有一天发现用不了的，在此之前是正常使用的；
电脑2：下面截图是我笔记本的报错截图，我用手机热点和笔记本连接以后可以正常传输和使用，断开热点手机和笔记本尝试连接同一个WiFi以后，就报下面截图的错误了
![image](https://github.com/user-attachments/assets/879dc837-bb65-4aab-990f-a9f8f016c62c)

**Comment by yeyt97** [comment]
看着像是配置文件解析的问题，是不是改错配置文件了。
另外新版发了，试试新版吧。

**Comment by iiiiiiu** [comment]
新版本已经可以啦，谢谢大大
