### ISSUE TITLE
希望能够整合到windows右键菜单的发送到当中

### ISSUE THREAD

**Issue by xiaoji235** [yeyt97/AirDropPlus#19]
非常好的程序，如果能够整合到右键菜单的发送到就完美了
![SharedScreenshot](https://github.com/user-attachments/assets/331b148e-ee99-430e-b133-e9af07b5b30c)

**Comment by yeyt97** [comment]
目前的原理是在windows上开一个http服务器，快捷指令发送http请求以获取或发送文件。在右键菜单发送这样属于主动推送了，实现不了
