### ISSUE TITLE
校园网环境下请求超时，是不是要保证在同一wifi下？

### ISSUE THREAD

**Issue by elmliu** [yeyt97/AirDropPlus#2]

**Comment by LanYanY** [comment]
是的，校园网可能要指定ip才行

**Comment by yeyt97** [comment]
最好能自己装一个路由器

**Comment by lhz07** [comment]
这个软件的本质其实就是局域网文件共享，然而校园网一般都会把局域网功能关掉。也就是说，即使连的是同一个校园网WiFi也不能用。
如果想在学校用的话，可以用电脑开热点给手机，或手机开热点给电脑

**Comment by a1078619054** [comment]
我配置到主机名意识到需要在同一局域网下，那需求好像也没那么大了。。。

**Comment by lhz07** [comment]
AirDrop
发自我的 iPhone

在 2024年1月22日，18:50，DarrenPig ***@***.***&gt; 写道：


﻿

 
但AirDrop服务的本身原理就在于局域网同步啊
 image.png (view on web) 嘿嘿
