### ISSUE TITLE
pc to ios？

### ISSUE THREAD

**Issue by GANailuo** [yeyt97/AirDropPlus#3]
Forgive my poor basic Python, I would like to know how to send files from PC to iOS, if you can help me then really thank you

**Comment by yeyt97** [comment]
Copy the file you want to send on the PC, and then run the shortcut directly (don't run it in the share menu)

**Comment by GANailuo** [comment]
Thank you so much, I have mastered it. Thank you for sharing this tool. I will share this tool with people around me who have the same working environment.
